### ISSUE TITLE
When running 'npm run development' index.js can't be found

### ISSUE THREAD

**Issue by santiagovdk** [kamleshchandnani/nextjs-serverless#1]
Hi, when I run the project using:

`npm run development
`

The server throws the following error when accessing http://localhost:8000/

> Error: Cannot find module './pages/index.js'
>     at webpackContextResolve (webpack:///./build/serverless_sync_^\.\/pages.*\.js$?:12:11)
>     at webpackContext (webpack:///./build/serverless_sync_^\.\/pages.*\.js$?:7:11)
>     at eval (webpack:///./src/server/serverless.js?:25:91)
>     at Layer.handle [as handle_request] (/Users/vdek/repo/mb/node_modules/express/lib/router/layer.js:95:5)
>     at next (/Users/vdek/repo/mb/node_modules/express/lib/router/route.js:137:13)
>     at Route.dispatch (/Users/vdek/repo/mb/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request] (/Users/vdek/repo/mb/node_modules/express/lib/router/layer.js:95:5)
>     at /Users/vdek/repo/mb/node_modules/express/lib/router/index.js:281:22
>     at Function.process_params (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:275:10)
>     at compression (/Users/vdek/repo/mb/node_modules/compression/index.js:220:5)
>     at Layer.handle [as handle_request] (/Users/vdek/repo/mb/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:317:13)
>     at /Users/vdek/repo/mb/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:275:10)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:47:33)
>     at xXssProtection (/Users/vdek/repo/mb/node_modules/x-xss-protection/index.js:26:7)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:51:7)
>     at nosniff (/Users/vdek/repo/mb/node_modules/dont-sniff-mimetype/index.js:4:5)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:51:7)
>     at ienoopen (/Users/vdek/repo/mb/node_modules/ienoopen/index.js:4:5)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:51:7)
>     at hsts (/Users/vdek/repo/mb/node_modules/hsts/index.js:42:5)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:51:7)
>     at hidePoweredBy (/Users/vdek/repo/mb/node_modules/hide-powered-by/index.js:12:7)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:51:7)
>     at frameguard (/Users/vdek/repo/mb/node_modules/frameguard/index.js:38:5)
>     at internalNext (/Users/vdek/repo/mb/node_modules/helmet/index.js:51:7)
>     at helmet (/Users/vdek/repo/mb/node_modules/helmet/index.js:54:5)
>     at Layer.handle [as handle_request] (/Users/vdek/repo/mb/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:317:13)
>     at /Users/vdek/repo/mb/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:275:10)
>     at expressInit (/Users/vdek/repo/mb/node_modules/express/lib/middleware/init.js:40:5)
>     at Layer.handle [as handle_request] (/Users/vdek/repo/mb/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:317:13)
>     at /Users/vdek/repo/mb/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:275:10)
>     at query (/Users/vdek/repo/mb/node_modules/express/lib/middleware/query.js:45:5)
>     at Layer.handle [as handle_request] (/Users/vdek/repo/mb/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:317:13)
>     at /Users/vdek/repo/mb/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:275:10)
>     at Function.handle (/Users/vdek/repo/mb/node_modules/express/lib/router/index.js:174:3)
>     at Function.handle (/Users/vdek/repo/mb/node_modules/express/lib/application.js:174:10)
>     at Server.app (/Users/vdek/repo/mb/node_modules/express/lib/express.js:39:9)
>     at Server.emit (events.js:189:13)
>     at Server.EventEmitter.emit (domain.js:459:23)
>     at parserOnIncoming (_http_server.js:676:12)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
>

**Comment by santiagovdk** [comment]
It seems to be a nextjs version issue. When upgrading to 9. Working on finding a possible fix.
